/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.jip8;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

public class App {
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            var console_frame = new JFrame("JIP 8");


            console_frame.setSize(200, 200);
            console_frame.setVisible(true);
            console_frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        });
    }
}
